# Limpieza, Organización y Reconstrucción del Conjunto de Datos Académico por Área de Formación
**Nombre del proyecto**: Predicción de deserción estudiantil en programas de Ingeniería<br>
**Programa académico**: Ingeniería de Sistemas y Computación<br>
**Sede**: UNIDAD REGIONAL, SEDE FUSAGASUGÁ<br>
**Elaborado por**: Jesús Villarraga<br>
**Propósito**: Este cuadernillo busca consolidar un conjunto de datos limpio y validado con información académica y situacional de estudiantes, para fines de análisis estadístico, diagnóstico institucional.

In [1]:
#librerias
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('../data/REA 2019 en adelante 05022025.xlsx')
df.head()

,PERIODO,FACULTAD,UNIDAD,PENSUM,DOCUMENTO,NOMBRES,MATRICULA_ACTUAL,SITUACION_ACTUAL,CATEGORIA_ACTUAL,CODIGO,CAMPO,REA,APROBACION
0,2019-1,FACULTAD DE CIENCIAS ADMINISTRATIVAS ECONÓMICA...,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",ADMINISTRACION DE EMPRESAS 2007,1000017416,VALERO PUERTO ANDRES FELIPE,SIN MATRICULA,GRADUADO,ANTIGUO,102007210,PENSAMIENTO ADMINISTRATIVO II,3.6,APROBADO
1,2019-1,FACULTAD DE CIENCIAS ADMINISTRATIVAS ECONÓMICA...,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",ADMINISTRACION DE EMPRESAS 2007,1000017416,VALERO PUERTO ANDRES FELIPE,SIN MATRICULA,GRADUADO,ANTIGUO,102007316,LEGISLACION LABORAL,4.2,APROBADO
2,2019-1,FACULTAD DE CIENCIAS ADMINISTRATIVAS ECONÓMICA...,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",ADMINISTRACION DE EMPRESAS 2007,1000017416,VALERO PUERTO ANDRES FELIPE,SIN MATRICULA,GRADUADO,ANTIGUO,102007319,ESTADISTICA II,3.8,APROBADO
3,2019-1,FACULTAD DE CIENCIAS ADMINISTRATIVAS ECONÓMICA...,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",ADMINISTRACION DE EMPRESAS 2007,1000017416,VALERO PUERTO ANDRES FELIPE,SIN MATRICULA,GRADUADO,ANTIGUO,102007315,CONTABILIDAD GENERAL,3.4,APROBADO
4,2019-1,FACULTAD DE CIENCIAS ADMINISTRATIVAS ECONÓMICA...,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",ADMINISTRACION DE EMPRESAS 2007,1000017416,VALERO PUERTO ANDRES FELIPE,SIN MATRICULA,GRADUADO,ANTIGUO,TR1002007316,INGLES III,3.9,APROBADO

In [3]:
pd.set_option('display.max_rows', 100)
df['PENSUM'].value_counts()

PENSUM
ADMINISTRACION DE EMPRESAS 2007                                           135716
CONTADURIA PUBLICA 2008                                                   135675
INGENIERIA DE SISTEMAS 2013                                                73196
INGENIERIA INDUSTRIAL                                                      53683
CIENCIAS DEL DEPORTE Y LA EDUCACION FISICA 2018                            37352
ADMINISTRACION DE EMPRESAS 2020 FUSAGASUGÁ                                 36697
INGENIERIA AMBIENTAL 20082                                                 35433
INGENIERÍA DE SISTEMAS Y COMPUTACIÓN 2020 -  FACATATIVÁ                    27214
INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSAGASUGA                       25827
ZOOTECNIA 2007                                                             23576
INGENIERIA ELECTRONICA 2007                                                20118
ENFERMERIA 2009                                                            19053
ADMINISTRACIÓN DE EMPRESAS 2020 FACATATIVÁ                                 18850
PSICOLOGIA 2018                                                            18593
CONTADURIA PUBLICA 2024                                                    17707
ZOOTECNIA 2020 - FUSAGASUGÁ                                                17111
INGENIERIA AGRONOMICA 2020 - EXT. FACATATIVA                               16757
INGENIERIA AGRONOMICA 2013                                                 16532
INGENIERIA AGRONOMICA 2020 - FUSAGASUGA                                    16425
CIENCIAS DEL DEPORTE Y LA EDUCACION FISICA - 2007                          16370
MUSICA 2010 1                                                              16342
ADMINISTRACIÓN DE EMPRESAS 2020 CHÍA                                       16247
INGENIERIA DE SISTEMAS Y COMPUTACION 2022 CHIA                             15917
ADMINISTRACIÓN DE EMPRESAS 2020 UBATE                                      15742
INGENIERIA AMBIENTAL 2020 - FACATATIVÁ                                     13749
INGENIERIA INDUSTRIAL 2022                                                 13467
CONTADURIA PUBLICA 2024 - FUSAGASUGA                                       12692
LICENCIATURA EN CIENCIAS SOCIALES 2018                                     12284
INGENIERIA AMBIENTAL 2020 GIRARDOT                                         12251
LIC. EN EDUC. BAS. CON ENF.  EN EDUCACION FISICA, RECREACION Y DEPORTE     11165
PSICOLOGIA 2011                                                             8580
PROFESIONAL EN CIENCIAS DEL DEPORTE 2022                                    8149
ADMINISTRACION DE EMPRESAS 2024 GIRARDOT                                    8113
TECNOLOGIA EN DESARROLLO DE SOFTWARE 2011                                   7820
SEMESTRE AVANZADO - ESPECIALIZACION EN GESTION DE SISTEMAS DE INFORMAC      5993
ZOOTECNIA 2020 - SEC. UBATE                                                 5938
TECNOLOGIA EN GESTION TURISTICA Y HOTELERA 2008-2                           5627
INGENIERIA DE SISTEMAS Y COMPUTACION 2024 UBATÉ                             5272
ESP. GERENCIA PARA EL DESARROLLO ORGANIZACIONAL                             5159
INGENIERIA DE SOFTWARE 2022 SOACHA                                          4997
INGENIERIA ELECTRONICA 2024                                                 4503
SEMESTRE AVANZADO - ESP. EN GERENCIA PARA EL DESARROLLO ORGANIZACIONAL      4319
ESPECIALIZACION EN GESTION DE SISTEMAS DE INFORMACION GERENCIAL             3572
LIC.EN EDUC.BASICA/ENF/HUMAN/LENG/CAST/ING 2007                             3249
ESPECIALIZACION EN EDUCACION  AMBIENTAL Y DESARROLLO DE LA COMUNIDAD        3225
TECNOLOGIA EN CARTOGRAFIA                                                   3102
ENFERMERIA 2023                                                             3094
SEMESTRE AVANZADO - ESPECIALIZACION EN EDUCACION AMBIENTAL Y DESARROLL      2967
MAESTRIA EN EDUCACION                                                       2514
ARMONIZACIÓN GRADO 9 - EXTENSION SOACHA                                     2094
LICENCIATURA EN MATEMATICAS-2007                                            2091
POSGRADOS                                                                   1900
INGENIERIA DE SOFTWARE 2023 GIRARDOT                                        1544
LIC. EN EDUCACION BASICA CON ENFASIS EN CIENCIAS SOCIALES 2012              1160
ESP. EN PROCESOS PEDAGOGICOS DEL ENTRENAMIENTO DEPORTIVO                     980
LICENCIATURA EN EDUCACIÓN FÍSICA RECREACIÓN Y DEPORTES 2024                  858
ARMONIZACIÓN GRADO 10 - EXTENSION SOACHA                                     728
SEMESTRE AVANZADO - ESPECIALIZACION EN NEGOCIOS Y COMERCIO ELECTRONICO       721
MAESTRIA EN CIENCIAS AMBIENTALES                                             650
ESPECIALIZACION EN NEGOCIOS Y COMERCIO ELECTRONICA                           640
INGENIERIA DE SISTEMAS 2007                                                  545
ARMONIZACIÓN GRADO 11 - EXTENSION SOACHA                                     397
INGENIERÍA MECATRÓNICA 2024                                                  392
SEMESTRE AVANZADO - ESPECIALIZACIÓN EN GERENCIA PARA LA TRANSFORMACION       331
ESPECIALIZACION EN EDUCACION AMBIENTAL Y DESARROLLO DE LA COMUNIDAD          318
ESPECIALIZACIÓN EN GERENCIA PARA LA TRANSFORMACION DIGITAL                   304
DOCTORADO EN CIENCIAS DE LA EDUCACION                                        298
ESPECIALIZACION EN MARKETING DIGITAL                                         275
CONTADURIA PUBLICA - PE                                                      151
SEMESTRE AVANZADO - PROCESOS PEDAGÓGICOS DEL ENTRENAMIENTO DEPORTIVO         135
SEMESTRE AVANZADO - ESPECIALIZACION EN GESTION PÚBLICA                       125
ADMINISTRACION DE EMPRESAS 2007 - PE                                         108
CIENCIAS DEL DEPORTE Y LA EDUCACION FISICA 2018 -PE                          104
POSGRADO                                                                      90
INGENIERIA DE SISTEMAS Y COMPUTACION 2020-PE                                  83
ESPECIALIZACION EN AGRONEGOCIOS SOSTENIBLES                                   79
SEMESTRE AVANZADO - ESPECIALIZACION EN MARKETING DIGITAL                      75
SEMESTRE AVANZADO - ESPECIALIZACION EN ANALÍTICA APLICADA A NEGOCIOS          75
ESPECIALIZACION EN GESTION PÚBLICA                                            55
INGENIERIA AMBIENTAL 2020-PE                                                  50
INGENIERIA AGRONOMICA 2007                                                    49
SEMESTRE AVANZADO - ESPECIALIZACION EN AGRONEGOCIOS SOSTENIBLES               45
SEMESTRE AVANZADO - MAESTRIA EN EDUCACION                                     42
ADMINISTRACION DE EMPRESAS 2020-PE                                            42
INGENIERIA AGRONOMICA 2020-PE                                                 40
TITULACION ESPECIALIZACION EN GESTION DE SISTEMAS DE INFORMACION GEREN        36
INGENIERIA INDUSTRIAL-PE                                                      35
INGENIERIA ELECTRONICA 2007 - PE                                              25
ADMINISTRACION AGROPECUARIA 2007                                              23
INGENIERIA DE SISTEMAS 2013-PE                                                17
LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN CIENCIAS SOCIALES 2007        11
LICENCIATURA EN CIENCIAS SOCIALES 2018 - PE                                    8
SEMESTRE AVANZADO - MAESTRIA EN CIENCIAS AMBIENTALES                           4
ESPECIALIZACION  EN  GERENCIA PARA EL DESARROLLO ORGANIZACIONAL                3
ADMINISTRACIÓN DE EMPRESAS 1994                                                1
MUSICA 1999                                                                    1
Name: count, dtype: int64

In [4]:
pensum_filtro = [
    "INGENIERIA DE SISTEMAS 2013",
    "INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSAGASUGA"
]
df_filtrado = df[df['PENSUM'].isin(pensum_filtro)]

In [5]:
df_filtrado.head()

,PERIODO,FACULTAD,UNIDAD,PENSUM,DOCUMENTO,NOMBRES,MATRICULA_ACTUAL,SITUACION_ACTUAL,CATEGORIA_ACTUAL,CODIGO,CAMPO,REA,APROBACION
6659,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,612013421,BASES DE DATOS,4.5,APROBADO
6660,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,612013420,FISICA III Y LABORATORIO,3.4,APROBADO
6661,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,612007533,SISTEMA DE INFORMACION,3.6,APROBADO
6662,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,612013422,BIOLOGIA,3.4,APROBADO
6663,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,612007424,ECUACIONES DIFERENCIALES,4.5,APROBADO

In [6]:
df_filtrado["SITUACION_ACTUAL"].value_counts()

SITUACION_ACTUAL
GRADUADO                               38476
ACTIVO                                 32879
EXCLUIDO ASIMILACION DE PENSUM         10896
EXCLUIDO TRANSFERENCIA INTERNA SA       4877
EXCLUIDO NO RENOVACION DE MATRICULA     4211
EXCLUIDO BAJO RENDIMIENTO               3000
INACTIVO                                2914
EXCLUIDO CANCELACION SEMESTRE            879
EXCLUIDO TRANSFERENCIA INTERNA           694
REVISION CARPETA GRADO                   126
SUSPENSION UN PERIODO ACADEMICO           61
PROCESO DE VERIFICACION                    7
SUSPENDIDO                                 3
Name: count, dtype: int64

Se construye una nueva columna que permita identificar cuando un estudiante perdio un espacio académico

In [7]:
df_filtrado['BAJO_RENDIMIENTO_REA'] = (df_filtrado['REA'] < 3.0).astype(int)
df_filtrado['REA'] = pd.to_numeric(df_filtrado['REA'], errors='coerce')

C:\Users\User\AppData\Local\Temp\ipykernel_28228\3473352509.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado['BAJO_RENDIMIENTO_REA'] = (df_filtrado['REA'] < 3.0).astype(int)
C:\Users\User\AppData\Local\Temp\ipykernel_28228\3473352509.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado['REA'] = pd.to_numeric(df_filtrado['REA'], errors='coerce')

In [8]:
df_filtrado['BAJO_RENDIMIENTO_REA'].value_counts()

BAJO_RENDIMIENTO_REA
0    89524
1     9499
Name: count, dtype: int64

Se generara una columna por area de formación esto con el fin de integrar la información de los espacios académicos de una mejor manera

In [9]:
# limpiar los valores antes de contar y listar los únicos
df_filtrado['CAMPO'] = (
    df_filtrado['CAMPO']
    .astype(str)  # Por si hay valores que no son string
    .str.strip()  # Quitar espacios al inicio y fin
    .str.replace('\xa0', ' ', regex=False)  # Reemplazar caracteres no imprimibles
    .str.replace('\n', ' ', regex=False)
    .str.replace('\s+', ' ', regex=True)
    .str.upper()  # Homogeneizar mayúsculas
)

<>:8: SyntaxWarning: invalid escape sequence '\s'
<>:8: SyntaxWarning: invalid escape sequence '\s'
C:\Users\User\AppData\Local\Temp\ipykernel_28228\743972264.py:8: SyntaxWarning: invalid escape sequence '\s'
  .str.replace('\s+', ' ', regex=True)
C:\Users\User\AppData\Local\Temp\ipykernel_28228\743972264.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado['CAMPO'] = (

In [10]:
valores_unicos_limpios = df_filtrado['CAMPO'].unique()
cantidad_limpios = df_filtrado['CAMPO'].nunique()

In [11]:
print(valores_unicos_limpios)
print(f"Cantidad de valores únicos (limpios): {cantidad_limpios}")

['BASES DE DATOS' 'FISICA III Y LABORATORIO' 'SISTEMA DE INFORMACION'
 'BIOLOGIA' 'ECUACIONES DIFERENCIALES' 'CONTABILIDAD GENERAL'
 'INGENIERIA DE SOFTWARE I' 'MATEMATICAS II' 'FUNDAMENTOS DE ECONOMIA'
 'SISTEMAS OPERATIVOS' 'MATEMATICAS DISCRETAS' 'MATEMATICAS I'
 'ALGEBRA LINEAL' 'INGLES I' 'FUNDAMENTOS DE INGENIERIA'
 'LOGICA Y ALGORITMIA' 'ETICA E IDENTIDAD INSTITUCIONAL'
 'FISICA I Y LABORATORIO' 'FUNDAMENTOS DE ELECTRONICA DIGITAL'
 'HABILIDADES LECTO-ESCRITORAS' 'PROGRAMACION I'
 'ESTRUCTURA DE INFORMACION' 'ARQUITECTURA DE COMPUTADORES'
 'FISICA II Y LABORATORIO' 'ELECTIVA FORMAC. GRAL INTEGRAL I'
 'PROGRAMACION II' 'MATEMATICAS III' 'CONSTITUCION Y DEMOCRACIA'
 'PENSAMIENTO SISTEMATICO TGS' 'MATEMATICAS ESPECIALES' 'INGLES II'
 'INVESTIGACION II' 'ELECTIVA PROFESIONAL' 'ELECTIVA PROFESIONAL III'
 'INVESTIGACION DE OPERACIONES I' 'ADMINISTRACION Y GESTION EMPRESARIAL'
 'LINEA DE PROFUNDIZACION I' 'ESTADISTICA Y PROBABILIDADES'
 'INTELIGENCIA ARTIFICIAL' 'INVESTIGACION DE OPERACIONES II'
 'EVALUACION DE PROYECTOS' 'PLANEACION ESTRATEGICA'
 'INGENIERIA DE SOFTWARE II' 'LEGISLACION EN INFORMATICA'
 'COMUNICACION DE DATOS I' 'ANALISIS NUMERICO' 'LINEA DE PROFUNDACION III'
 'INVESTIGACION I' 'COMUNICACION DE DATOS II' 'ELECTIVA PROFESIONAL II'
 'MODELACION' 'LINEA DE PROFUNDIZACION II'
 'AUDITORIA Y SEGURIDAD INFORMATICA' 'TRABAJO DE GRADO'
 'ELECTIVA FORMACION GRAL INTEGRAL II' 'GERENCIA INFORMATICA'
 'CALCULO INTEGRAL' 'FUNDAMENTOS DE ELECTRÓNICA' 'FISICA I'
 'LENGUA EXTRANJERA I' 'DIAGNOSTICO Y NIVELATORIO LENGUA EXTRANJERA I'
 'FUNDAMENTOS DE INGENIERÍA' 'MATEMÁTICAS DISCRETAS' 'CALCULO DIFERENCIAL'
 'CIUDADANIA DEL SIGLO 21' 'PENSAMIENTO ALGORÍTMICO' 'ÁLGEBRA LINEAL'
 'BASE DE DATOS' 'FISICA II' 'SISTEMAS DE INFORMACION'
 'COMUNICACIÓN Y LECTURA CRÍTICA I'
 'DIAGNOSTICO Y NIVELATORIO COMUNICACIÓN Y LECTURA CRÍTICA I'
 'CIENCIA, TECNOLOGIA E INNOVACION II' 'LENGUA EXTRANJERA II'
 'FUNDAMENTOS ADMINISTRATIVOS' 'ANÁLISIS NUMÉRICO' 'COMUNICACIÓN DE DATOS'
 'PROGRAMACIÓN I' 'ESTRUCTURAS DE INFORMACIÓN' 'PROGRAMACIÓN II'
 'FISICA III' 'CALCULO MULTIVARIADO'
 'DIAGNOSTICO Y NIVELATORIO CIUDADANIA DEL SIGLO 21'
 'REDES Y COMUNICACIÓN' 'ESTADÍSTICA,PROBABILIDAD E INFERENCIA'
 'GERENCIA DE PROYECTOS' 'CIENCIA, TECNOLOGIA E INNOVACION I'
 'DIAGNOSTICO Y NIVELATORIO RAZONAMIENTO LÓGICO Y CUANTITATIVO'
 'PENSAMIENTO SISTÉMICO Y AUTOMATIZACIÓN'
 'COMUNICACIÓN Y LECTURA CRÍTICA II' 'RAZONAMIENTO LÓGICO Y CUANTITATIVO'
 'DIAGNOSTICO Y NIVELATORIO CIENCIA, TECNOLOGIA E INNOVACION I'
 'DIAGNOSTICO Y NIVELATORIO EMPRENDIMIENTO E INNOVACION I'
 'CATEDRA GENERACION SIGLO 21' 'LENGUA EXTRANJERA III'
 'LENGUA EXTRANJERA IV' 'EMPRENDIMIENTO E INNOVACION I' 'NETWORKING'
 'CIENCIA DE DATOS' 'OPERATIVA' 'SEGURIDAD INFORMÁTICA'
 'EMPRENDIMIENTO E INNOVACION II' 'LENGUAJES Y AUTOMATAS'
 'CIENCIA Y TECNOLOGIA E INNOVACION III'
 'GESTIÓN DE PROYECTOS DE SOFTWARE'
 'MEJORAMIENTO DE PROCESOS DE DESARROLLO'
 'METODOLOGÍAS DE DESARROLLO TRADICIONALES'
 'PROCESOS DE GESTIÓN DE CALIDAD DE SOFTWARE' 'PROFUNDIZACION I'
 'ESTRUCTURA Y ARQUITECTURA DE SOFTWARE' 'REDES CONVERGENTES'
 'REDES WAN DEFINIDAS POR SOFTWARE' 'INFRAESTRUCTURAS INALÁMBRICAS'
 'SEGURIDAD PERIMETRAL' 'GESTIÓN DE INFRAESTRUCTURAS DE TI'
 'PROFUNDIZACION II' 'OPCION DE GRADO' 'CATEDRA GENERACION SIGLO 21-NR'
 'OPCIÓN DE GRADO - SUSTENTACIÓN']
Cantidad de valores únicos (limpios): 119

In [12]:
area_formacion_dict = {
    # INGENIERÍA APLICADA
    'BASES DE DATOS': 'INGENIERÍA APLICADA',
    'ESTRUCTURA DE INFORMACION': 'INGENIERÍA APLICADA',
    'ESTRUCTURAS DE INFORMACIÓN': 'INGENIERÍA APLICADA',
    'SISTEMA DE INFORMACION': 'INGENIERÍA APLICADA',
    'SISTEMAS DE INFORMACION': 'INGENIERÍA APLICADA',
    'INGENIERIA DE SOFTWARE I': 'INGENIERÍA APLICADA',
    'INGENIERIA DE SOFTWARE II': 'INGENIERÍA APLICADA',
    'SEGURIDAD INFORMÁTICA': 'INGENIERÍA APLICADA',
    'NETWORKING': 'INGENIERÍA APLICADA',
    'CIENCIA DE DATOS': 'INGENIERÍA APLICADA',
    'GERENCIA DE PROYECTOS': 'INGENIERÍA APLICADA',
    'FUNDAMENTOS DE ELECTRÓNICA': 'INGENIERÍA APLICADA',
    'ARQUITECTURA DE COMPUTADORES': 'INGENIERÍA APLICADA',
    'SISTEMAS OPERATIVOS': 'INGENIERÍA APLICADA',
    'COMUNICACION DE DATOS I': 'INGENIERÍA APLICADA',
    'COMUNICACION DE DATOS II': 'INGENIERÍA APLICADA',
    'COMUNICACIÓN DE DATOS': 'INGENIERÍA APLICADA',
    'REDES Y COMUNICACIÓN': 'INGENIERÍA APLICADA',
    'INTELIGENCIA ARTIFICIAL': 'INGENIERÍA APLICADA',
    'LENGUAJES Y AUTOMATAS': 'INGENIERÍA APLICADA',
    'OPERATIVA': 'INGENIERÍA APLICADA',
    'MATEMATICAS ESPECIALES': 'INGENIERÍA APLICADA',
    'MODELACION': 'INGENIERÍA APLICADA',
    'PROFUNDIZACION I': 'INGENIERÍA APLICADA',
    'PROFUNDIZACION II': 'INGENIERÍA APLICADA',
    'OPCION DE GRADO': 'INGENIERÍA APLICADA',
    'OPCIÓN DE GRADO - SUSTENTACIÓN': 'INGENIERÍA APLICADA',
    'GESTIÓN DE PROYECTOS DE SOFTWARE': 'INGENIERÍA APLICADA',
    'MEJORAMIENTO DE PROCESOS DE DESARROLLO': 'INGENIERÍA APLICADA',
    'METODOLOGÍAS DE DESARROLLO TRADICIONALES': 'INGENIERÍA APLICADA',
    'PROCESOS DE GESTIÓN DE CALIDAD DE SOFTWARE': 'INGENIERÍA APLICADA',
    'ESTRUCTURA Y ARQUITECTURA DE SOFTWARE': 'INGENIERÍA APLICADA',
    'REDES CONVERGENTES': 'INGENIERÍA APLICADA',
    'REDES WAN DEFINIDAS POR SOFTWARE': 'INGENIERÍA APLICADA',
    'INFRAESTRUCTURAS INALÁMBRICAS': 'INGENIERÍA APLICADA',
    'SEGURIDAD PERIMETRAL': 'INGENIERÍA APLICADA',
    'GESTIÓN DE INFRAESTRUCTURAS DE TI': 'INGENIERÍA APLICADA',
    'INVESTIGACION DE OPERACIONES I': 'INGENIERÍA APLICADA',
    'INVESTIGACION DE OPERACIONES II': 'INGENIERÍA APLICADA',
    'EVALUACION DE PROYECTOS': 'INGENIERÍA APLICADA',
    'LEGISLACION EN INFORMATICA': 'INGENIERÍA APLICADA',
    'AUDITORIA Y SEGURIDAD INFORMATICA':'INGENIERÍA APLICADA',
    'GERENCIA INFORMATICA':'INGENIERÍA APLICADA',
    'LINEA DE PROFUNDIZACION I':'INGENIERÍA APLICADA',
    'LINEA DE PROFUNDIZACION II':'INGENIERÍA APLICADA',
    'LINEA DE PROFUNDACION III':'INGENIERÍA APLICADA',
    'ELECTIVA PROFESIONAL':'INGENIERÍA APLICADA',
    'ELECTIVA PROFESIONAL II':'INGENIERÍA APLICADA',
    'ELECTIVA PROFESIONAL III':'INGENIERÍA APLICADA',
    'TRABAJO DE GRADO':'INGENIERÍA APLICADA',
    'BASE DE DATOS':'INGENIERÍA APLICADA',
    'FUNDAMENTOS DE ELECTRONICA DIGITAL':'INGENIERÍA APLICADA',


    # CIENCIAS BÁSICAS
    'CALCULO DIFERENCIAL': 'CIENCIAS BÁSICAS',
    'CALCULO INTEGRAL': 'CIENCIAS BÁSICAS',
    'CALCULO MULTIVARIADO': 'CIENCIAS BÁSICAS',
    'ECUACIONES DIFERENCIALES': 'CIENCIAS BÁSICAS',
    'FISICA I': 'CIENCIAS BÁSICAS',
    'FISICA I Y LABORATORIO': 'CIENCIAS BÁSICAS',
    'FISICA II': 'CIENCIAS BÁSICAS',
    'FISICA II Y LABORATORIO': 'CIENCIAS BÁSICAS',
    'FISICA III': 'CIENCIAS BÁSICAS',
    'FISICA III Y LABORATORIO': 'CIENCIAS BÁSICAS',
    'BIOLOGIA':'CIENCIAS BÁSICAS',
    'MATEMATICAS II':'CIENCIAS BÁSICAS',
    'MATEMATICAS I':'CIENCIAS BÁSICAS',
    'MATEMATICAS III':'CIENCIAS BÁSICAS',

    # CIENCIAS BÁSICAS DE INGENIERÍA
    'ALGEBRA LINEAL': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'ÁLGEBRA LINEAL': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'MATEMATICAS DISCRETAS': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'MATEMÁTICAS DISCRETAS': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'ESTADISTICA Y PROBABILIDADES': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'ESTADÍSTICA,PROBABILIDAD E INFERENCIA': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'ANALISIS NUMERICO': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'ANÁLISIS NUMÉRICO': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'PENSAMIENTO ALGORÍTMICO': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'PROGRAMACION I': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'PROGRAMACIÓN I': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'PROGRAMACION II': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'PROGRAMACIÓN II': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'FUNDAMENTOS DE INGENIERIA': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'FUNDAMENTOS DE INGENIERÍA': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'PENSAMIENTO SISTEMICO TGS': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'PENSAMIENTO SISTÉMICO Y AUTOMATIZACIÓN': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'FUNDAMENTOS ADMINISTRATIVOS': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'PLANEACION ESTRATEGICA': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'PENSAMIENTO SISTEMATICO TGS': 'CIENCIAS BÁSICAS DE INGENIERÍA',
    'LOGICA Y ALGORITMIA': 'CIENCIAS BÁSICAS DE INGENIERÍA',

    # INSTITUCIONAL
    'CIUDADANIA DEL SIGLO 21': 'INSTITUCIONAL',
    'DIAGNOSTICO Y NIVELATORIO CIUDADANIA DEL SIGLO 21': 'INSTITUCIONAL',
    'LENGUA EXTRANJERA I': 'INSTITUCIONAL',
    'LENGUA EXTRANJERA II': 'INSTITUCIONAL',
    'LENGUA EXTRANJERA III': 'INSTITUCIONAL',
    'LENGUA EXTRANJERA IV': 'INSTITUCIONAL',
    'INGLES I': 'INSTITUCIONAL',
    'INGLES II': 'INSTITUCIONAL',
    'DIAGNOSTICO Y NIVELATORIO LENGUA EXTRANJERA I': 'INSTITUCIONAL',
    'COMUNICACIÓN Y LECTURA CRÍTICA I': 'INSTITUCIONAL',
    'COMUNICACIÓN Y LECTURA CRÍTICA II': 'INSTITUCIONAL',
    'DIAGNOSTICO Y NIVELATORIO COMUNICACIÓN Y LECTURA CRÍTICA I': 'INSTITUCIONAL',
    'RAZONAMIENTO LÓGICO Y CUANTITATIVO': 'INSTITUCIONAL',
    'DIAGNOSTICO Y NIVELATORIO RAZONAMIENTO LÓGICO Y CUANTITATIVO': 'INSTITUCIONAL',
    'CIENCIA, TECNOLOGIA E INNOVACION I': 'INSTITUCIONAL',
    'CIENCIA, TECNOLOGIA E INNOVACION II': 'INSTITUCIONAL',
    'CIENCIA Y TECNOLOGIA E INNOVACION III': 'INSTITUCIONAL',
    'DIAGNOSTICO Y NIVELATORIO CIENCIA, TECNOLOGIA E INNOVACION I': 'INSTITUCIONAL',
    'EMPRENDIMIENTO E INNOVACION I': 'INSTITUCIONAL',
    'EMPRENDIMIENTO E INNOVACION II': 'INSTITUCIONAL',
    'DIAGNOSTICO Y NIVELATORIO EMPRENDIMIENTO E INNOVACION I': 'INSTITUCIONAL',
    'CATEDRA GENERACION SIGLO 21': 'INSTITUCIONAL',
    'CATEDRA GENERACION SIGLO 21-NR': 'INSTITUCIONAL',
    'HABILIDADES LECTO-ESCRITORAS':'INSTITUCIONAL',
    'ELECTIVA FORMAC. GRAL INTEGRAL I':'INSTITUCIONAL',
    'ELECTIVA FORMACION GRAL INTEGRAL II':'INSTITUCIONAL',
    'CONSTITUCION Y DEMOCRACIA':'INSTITUCIONAL',
    'INVESTIGACION I':'INSTITUCIONAL',
    'INVESTIGACION II':'INSTITUCIONAL',
    'ADMINISTRACION Y GESTION EMPRESARIAL':'INSTITUCIONAL',
    'ETICA E IDENTIDAD INSTITUCIONAL':'INSTITUCIONAL',
    'CONTABILIDAD GENERAL':'INSTITUCIONAL',
    'FUNDAMENTOS DE ECONOMIA':'INSTITUCIONAL',
    'ELECTIVA FORMAC. GRAL INTEGRAL I':'INSTITUCIONAL',
    'ELECTIVA FORMACION GRAL INTEGRAL II':'INSTITUCIONAL'
}

In [13]:
df_filtrado['AREA_FORMACION'] = df_filtrado['CAMPO'].str.upper().map(area_formacion_dict).fillna('SIN ASIGNAR')

C:\Users\User\AppData\Local\Temp\ipykernel_28228\402974806.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado['AREA_FORMACION'] = df_filtrado['CAMPO'].str.upper().map(area_formacion_dict).fillna('SIN ASIGNAR')

In [14]:
df_filtrado

,PERIODO,FACULTAD,UNIDAD,PENSUM,DOCUMENTO,NOMBRES,MATRICULA_ACTUAL,SITUACION_ACTUAL,CATEGORIA_ACTUAL,CODIGO,CAMPO,REA,APROBACION,BAJO_RENDIMIENTO_REA,AREA_FORMACION
6659,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,612013421,BASES DE DATOS,4.5,APROBADO,0,INGENIERÍA APLICADA
6660,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,612013420,FISICA III Y LABORATORIO,3.4,APROBADO,0,CIENCIAS BÁSICAS
6661,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,612007533,SISTEMA DE INFORMACION,3.6,APROBADO,0,INGENIERÍA APLICADA
6662,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,612013422,BIOLOGIA,3.4,APROBADO,0,CIENCIAS BÁSICAS
6663,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,612007424,ECUACIONES DIFERENCIALES,4.5,APROBADO,0,CIENCIAS BÁSICAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015667,2025-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1076649906,AGUILAR PAEZ JUAN DAVID,SIN MATRICULA,ACTIVO,ANTIGUO,CAD612021104,PENSAMIENTO SISTÉMICO Y AUTOMATIZACIÓN,4.0,APROBADO,0,CIENCIAS BÁSICAS DE INGENIERÍA
1015668,2025-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1076649906,AGUILAR PAEZ JUAN DAVID,SIN MATRICULA,ACTIVO,ANTIGUO,CAD612021209,PROGRAMACIÓN I,3.3,APROBADO,0,CIENCIAS BÁSICAS DE INGENIERÍA
1015669,2025-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1076649906,AGUILAR PAEZ JUAN DAVID,SIN MATRICULA,ACTIVO,ANTIGUO,CAI1002020201,RAZONAMIENTO LÓGICO Y CUANTITATIVO,4.7,APROBADO,0,INSTITUCIONAL
1015670,2025-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1076649906,AGUILAR PAEZ JUAN DAVID,SIN MATRICULA,ACTIVO,ANTIGUO,CAD612021210,"ESTADÍSTICA,PROBABILIDAD E INFERENCIA",4.5,APROBADO,0,CIENCIAS BÁSICAS DE INGENIERÍA
1015671,2025-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1076649906,AGUILAR PAEZ JUAN DAVID,SIN MATRICULA,ACTIVO,ANTIGUO,CAD612021208,FISICA I,3.4,APROBADO,0,CIENCIAS BÁSICAS

In [15]:
df_filtrado["AREA_FORMACION"].value_counts()

AREA_FORMACION
INGENIERÍA APLICADA               40908
INSTITUCIONAL                     24237
CIENCIAS BÁSICAS DE INGENIERÍA    20242
CIENCIAS BÁSICAS                  13636
Name: count, dtype: int64

In [16]:
df_con_area = df_filtrado.copy()

las areas de formación son 4 por ende cada documento que implica un estudiante deberia de aparecer como máximo 4 veces

In [17]:
df_agrupado = df_filtrado.groupby(['DOCUMENTO', 'AREA_FORMACION'])['REA'].mean().reset_index()
df_agrupado

       DOCUMENTO                  AREA_FORMACION       REA
0         447383  CIENCIAS BÁSICAS DE INGENIERÍA  4.050000
1         447383             INGENIERÍA APLICADA  3.965000
2         447383                   INSTITUCIONAL  4.030000
3         477384  CIENCIAS BÁSICAS DE INGENIERÍA  4.110000
4         477384             INGENIERÍA APLICADA  2.710000
...          ...                             ...       ...
12209  G26094687                   INSTITUCIONAL  4.700000
12210  G36749919             INGENIERÍA APLICADA  4.433333
12211  G36749919                   INSTITUCIONAL  4.300000
12212  N01714804             INGENIERÍA APLICADA  4.200000
12213  N01714804                   INSTITUCIONAL  4.320000

[12214 rows x 3 columns]

In [18]:
df_filtrado = df_filtrado.drop(columns=['CODIGO'], errors='ignore')

Construimos una variable que permitiera identificar un estudiante cuantas materias ha perdido esto podria ser un indicador clave de deserción

In [19]:
# Crear la columna con el total de bajo rendimiento por estudiante
total_bajo_rendimiento = df_filtrado.groupby('DOCUMENTO')['BAJO_RENDIMIENTO_REA'].sum().reset_index()
total_bajo_rendimiento

        DOCUMENTO  BAJO_RENDIMIENTO_REA
0          447383                     0
1          477384                     1
2          589798                     0
3          628960                     3
4          649530                     1
...           ...                   ...
3372  99050101742                     5
3373  99112907730                     5
3374    G26094687                     0
3375    G36749919                     0
3376    N01714804                     0

[3377 rows x 2 columns]

In [20]:
# Renombramos la nueva columna
total_bajo_rendimiento = total_bajo_rendimiento.rename(columns={'BAJO_RENDIMIENTO_REA': 'TOTAL_BAJO_RENDIMIENTO_REA'})
total_bajo_rendimiento

        DOCUMENTO  TOTAL_BAJO_RENDIMIENTO_REA
0          447383                           0
1          477384                           1
2          589798                           0
3          628960                           3
4          649530                           1
...           ...                         ...
3372  99050101742                           5
3373  99112907730                           5
3374    G26094687                           0
3375    G36749919                           0
3376    N01714804                           0

[3377 rows x 2 columns]

In [21]:
# Unimos al DataFrame original (si quieres mantenerla allí)
df_filtrado = df_filtrado.merge(total_bajo_rendimiento, on='DOCUMENTO', how='left')
df_filtrado

,PERIODO,FACULTAD,UNIDAD,PENSUM,DOCUMENTO,NOMBRES,MATRICULA_ACTUAL,SITUACION_ACTUAL,CATEGORIA_ACTUAL,CAMPO,REA,APROBACION,BAJO_RENDIMIENTO_REA,AREA_FORMACION,TOTAL_BAJO_RENDIMIENTO_REA
0,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,BASES DE DATOS,4.5,APROBADO,0,INGENIERÍA APLICADA,1
1,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,FISICA III Y LABORATORIO,3.4,APROBADO,0,CIENCIAS BÁSICAS,1
2,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,SISTEMA DE INFORMACION,3.6,APROBADO,0,INGENIERÍA APLICADA,1
3,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,BIOLOGIA,3.4,APROBADO,0,CIENCIAS BÁSICAS,1
4,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,ECUACIONES DIFERENCIALES,4.5,APROBADO,0,CIENCIAS BÁSICAS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99018,2025-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1076649906,AGUILAR PAEZ JUAN DAVID,SIN MATRICULA,ACTIVO,ANTIGUO,PENSAMIENTO SISTÉMICO Y AUTOMATIZACIÓN,4.0,APROBADO,0,CIENCIAS BÁSICAS DE INGENIERÍA,0
99019,2025-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1076649906,AGUILAR PAEZ JUAN DAVID,SIN MATRICULA,ACTIVO,ANTIGUO,PROGRAMACIÓN I,3.3,APROBADO,0,CIENCIAS BÁSICAS DE INGENIERÍA,0
99020,2025-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1076649906,AGUILAR PAEZ JUAN DAVID,SIN MATRICULA,ACTIVO,ANTIGUO,RAZONAMIENTO LÓGICO Y CUANTITATIVO,4.7,APROBADO,0,INSTITUCIONAL,0
99021,2025-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1076649906,AGUILAR PAEZ JUAN DAVID,SIN MATRICULA,ACTIVO,ANTIGUO,"ESTADÍSTICA,PROBABILIDAD E INFERENCIA",4.5,APROBADO,0,CIENCIAS BÁSICAS DE INGENIERÍA,0
99022,2025-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1076649906,AGUILAR PAEZ JUAN DAVID,SIN MATRICULA,ACTIVO,ANTIGUO,FISICA I,3.4,APROBADO,0,CIENCIAS BÁSICAS,0

In [22]:
df_filtrado[df_filtrado["DOCUMENTO"]==1069750950]

,PERIODO,FACULTAD,UNIDAD,PENSUM,DOCUMENTO,NOMBRES,MATRICULA_ACTUAL,SITUACION_ACTUAL,CATEGORIA_ACTUAL,CAMPO,REA,APROBACION,BAJO_RENDIMIENTO_REA,AREA_FORMACION,TOTAL_BAJO_RENDIMIENTO_REA
16912,2019-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS 2013,1069750950,AREVALO RODRIGUEZ WILLIAM FABIAN,SIN MATRICULA,GRADUADO,ANTIGUO,TRABAJO DE GRADO,0.0,NO APROBADO,1,INGENIERÍA APLICADA,1

In [23]:
df_promedios = df_filtrado.groupby(['DOCUMENTO', 'AREA_FORMACION'])['REA'].mean().reset_index()
df_pivot = df_promedios.pivot(index='DOCUMENTO', columns='AREA_FORMACION', values='REA')
df_pivot = df_pivot.reset_index()
df_resumen = df_pivot.merge(total_bajo_rendimiento, on='DOCUMENTO', how='left')
df_pivot

AREA_FORMACION,DOCUMENTO,CIENCIAS BÁSICAS,CIENCIAS BÁSICAS DE INGENIERÍA,INGENIERÍA APLICADA,INSTITUCIONAL
0,447383,NaN,4.050000,3.965000,4.030000
1,477384,NaN,4.110000,2.710000,NaN
2,589798,3.975000,4.066667,4.380000,4.275000
3,628960,3.455556,3.670000,3.562963,3.783333
4,649530,NaN,NaN,3.066667,NaN
...,...,...,...,...,...
3372,99050101742,1.980000,NaN,2.366667,4.400000
3373,99112907730,0.000000,0.000000,0.000000,NaN
3374,G26094687,NaN,NaN,4.533333,4.700000
3375,G36749919,NaN,NaN,4.433333,4.300000
3376,N01714804,NaN,NaN,4.200000,4.320000

In [24]:
df_filtrado.columns

Index(['PERIODO', 'FACULTAD', 'UNIDAD', 'PENSUM', 'DOCUMENTO', 'NOMBRES',
       'MATRICULA_ACTUAL', 'SITUACION_ACTUAL', 'CATEGORIA_ACTUAL', 'CAMPO',
       'REA', 'APROBACION', 'BAJO_RENDIMIENTO_REA', 'AREA_FORMACION',
       'TOTAL_BAJO_RENDIMIENTO_REA'],
      dtype='object')

In [25]:
columnas_constantes = ['PERIODO', 'FACULTAD', 'UNIDAD', 'PENSUM', 'DOCUMENTO', 'NOMBRES', 'MATRICULA_ACTUAL', 'SITUACION_ACTUAL', 'CATEGORIA_ACTUAL',]  # por ejemplo
df_estudiantes = df_filtrado[columnas_constantes].drop_duplicates(subset='DOCUMENTO')

In [26]:
# Unir resumen de promedios por área
df_resumen = df_estudiantes.merge(df_pivot, on='DOCUMENTO', how='left')

# Unir total de bajo rendimiento
df_resumen = df_resumen.merge(total_bajo_rendimiento, on='DOCUMENTO', how='left')
df_resumen

,PERIODO,FACULTAD,UNIDAD,PENSUM,DOCUMENTO,NOMBRES,MATRICULA_ACTUAL,SITUACION_ACTUAL,CATEGORIA_ACTUAL,CIENCIAS BÁSICAS,CIENCIAS BÁSICAS DE INGENIERÍA,INGENIERÍA APLICADA,INSTITUCIONAL,TOTAL_BAJO_RENDIMIENTO_REA
0,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000148972,HERMOSILLA BUITRAGO ANGEL DANIEL,SIN MATRICULA,GRADUADO,ANTIGUO,3.766667,3.650000,3.791304,3.9375,1
1,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000178203,QUEMBA RUIZ NEYDER ALBERTO,SIN MATRICULA,EXCLUIDO NO RENOVACION DE MATRICULA,NUEVO REINGRESO,2.925000,2.700000,3.100000,3.2750,7
2,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000183874,LOPEZ BURGOS EDWIN ALEXANDER,SIN MATRICULA,EXCLUIDO TRANSFERENCIA INTERNA,ANTIGUO,3.340000,3.750000,4.100000,4.1000,2
3,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000185288,QUIROGA TORRES DAVID GERONIMO,SIN MATRICULA,GRADUADO,ANTIGUO,3.642857,4.116667,3.810714,4.2900,3
4,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, EXTENSIÓN CHÍA",INGENIERIA DE SISTEMAS 2013,1000239960,FORERO MARTINEZ ANDRES DAVID,SIN MATRICULA,GRADUADO,ANTIGUO,3.533333,4.050000,3.843478,4.0375,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3372,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1105465272,VILLARREAL CASTILLO DIEGO ANDRES,SIN MATRICULA,ACTIVO,ANTIGUO,NaN,4.788000,3.710000,4.3750,0
3373,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1105840288,GONZALEZ GONZALEZ GIOVANNI STIVEN,SIN MATRICULA,ACTIVO,ANTIGUO,NaN,4.346000,3.720000,4.0600,0
3374,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1110233645,RODRIGUEZ MENDOZA DANIEL ESTEBAN,SIN MATRICULA,ACTIVO,ANTIGUO,NaN,4.274000,3.860000,4.0800,0
3375,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1117502702,CUENCA MORENO OLIVER DANILO,SIN MATRICULA,ACTIVO,ANTIGUO,NaN,3.806000,4.300000,3.6650,0
3376,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,11951929,REYES CASTILLO BRAYAN MICHEL,SIN MATRICULA,ACTIVO,MOVILIDAD ACADEMICA ENTRANTE,NaN,NaN,4.076000,NaN,0

In [27]:
df_resumen_fusagasuga = df_resumen[df_resumen['UNIDAD'] == 'UNIDAD REGIONAL, SEDE FUSAGASUGÁ'].reset_index(drop=True)

In [28]:
df_resumen_fusagasuga

,PERIODO,FACULTAD,UNIDAD,PENSUM,DOCUMENTO,NOMBRES,MATRICULA_ACTUAL,SITUACION_ACTUAL,CATEGORIA_ACTUAL,CIENCIAS BÁSICAS,CIENCIAS BÁSICAS DE INGENIERÍA,INGENIERÍA APLICADA,INSTITUCIONAL,TOTAL_BAJO_RENDIMIENTO_REA
0,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1000136072,FORERO HERRERA TANIA NICKOLL,SIN MATRICULA,ACTIVO,CONTINUIDAD ACADEMICA - EGRESADO,3.553846,3.956154,3.951915,3.897200,2
1,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1000320087,MESA BLANCO LEONARDO JUAN,SIN MATRICULA,ACTIVO,ANTIGUO,3.310833,3.297368,3.661538,3.761000,9
2,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1000592838,BAUTISTA DIAZ DANIEL EDUARDO,SIN MATRICULA,ACTIVO,CONTINUIDAD ACADEMICA - EGRESADO,3.475000,3.625714,3.960278,3.890833,6
3,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1001346777,SUAREZ HEREDIA JUAN SEBASTIAN,SIN MATRICULA,EXCLUIDO BAJO RENDIMIENTO,ANTIGUO,3.171429,2.900000,3.100000,3.000000,7
4,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1003515700,ESCOBAR VASQUEZ JENIFFER DAYANA,SIN MATRICULA,EXCLUIDO BAJO RENDIMIENTO,ANTIGUO,3.328571,2.623529,3.900000,3.485714,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1201,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1105465272,VILLARREAL CASTILLO DIEGO ANDRES,SIN MATRICULA,ACTIVO,ANTIGUO,NaN,4.788000,3.710000,4.375000,0
1202,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1105840288,GONZALEZ GONZALEZ GIOVANNI STIVEN,SIN MATRICULA,ACTIVO,ANTIGUO,NaN,4.346000,3.720000,4.060000,0
1203,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1110233645,RODRIGUEZ MENDOZA DANIEL ESTEBAN,SIN MATRICULA,ACTIVO,ANTIGUO,NaN,4.274000,3.860000,4.080000,0
1204,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1117502702,CUENCA MORENO OLIVER DANILO,SIN MATRICULA,ACTIVO,ANTIGUO,NaN,3.806000,4.300000,3.665000,0
1205,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,11951929,REYES CASTILLO BRAYAN MICHEL,SIN MATRICULA,ACTIVO,MOVILIDAD ACADEMICA ENTRANTE,NaN,NaN,4.076000,NaN,0

In [29]:
df_resumen_fusagasuga.duplicated().sum()

np.int64(0)

In [30]:
df_resumen_fusagasuga.isnull().mean().round(4) * 100

PERIODO                            0.00
FACULTAD                           0.00
UNIDAD                             0.00
PENSUM                             0.00
DOCUMENTO                          0.00
NOMBRES                            0.00
MATRICULA_ACTUAL                   0.00
SITUACION_ACTUAL                   0.00
CATEGORIA_ACTUAL                   0.00
CIENCIAS BÁSICAS                  25.87
CIENCIAS BÁSICAS DE INGENIERÍA     4.48
INGENIERÍA APLICADA                2.65
INSTITUCIONAL                      4.06
TOTAL_BAJO_RENDIMIENTO_REA         0.00
dtype: float64

In [31]:
df_sin_ciencias_basicas = df_resumen_fusagasuga[df_resumen_fusagasuga['CIENCIAS BÁSICAS'].isna()].reset_index(drop=True)
df_sin_ciencias_basicas["SITUACION_ACTUAL"].value_counts()

SITUACION_ACTUAL
GRADUADO                               151
ACTIVO                                 100
INACTIVO                                22
EXCLUIDO NO RENOVACION DE MATRICULA     18
EXCLUIDO BAJO RENDIMIENTO               12
EXCLUIDO CANCELACION SEMESTRE            7
REVISION CARPETA GRADO                   1
SUSPENDIDO                               1
Name: count, dtype: int64

Hallando inconsistencias, no puede suceder que un graduado no vea todos los espacios académicos o que no tenga notas en alguna area de formación.

In [32]:
areas_clave = [
    'CIENCIAS BÁSICAS',
    'CIENCIAS BÁSICAS DE INGENIERÍA',
    'INGENIERÍA APLICADA',
    'INSTITUCIONAL'
]
inconsistentes = df_resumen_fusagasuga[
    (df_resumen_fusagasuga['SITUACION_ACTUAL'] == 'GRADUADO') &
    (df_resumen_fusagasuga[areas_clave].isna().any(axis=1))
]
inconsistentes

,PERIODO,FACULTAD,UNIDAD,PENSUM,DOCUMENTO,NOMBRES,MATRICULA_ACTUAL,SITUACION_ACTUAL,CATEGORIA_ACTUAL,CIENCIAS BÁSICAS,CIENCIAS BÁSICAS DE INGENIERÍA,INGENIERÍA APLICADA,INSTITUCIONAL,TOTAL_BAJO_RENDIMIENTO_REA
22,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS 2013,1000062185,FONSECA FIGUEROA JENIFFER VANESSA,SIN MATRICULA,GRADUADO,ANTIGUO,NaN,NaN,3.783333,4.0000,1
41,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS 2013,1000713504,MONSALVE DELIMA DAVID HERNANDO,SIN MATRICULA,GRADUADO,ANTIGUO,NaN,NaN,3.381818,3.8000,2
42,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS 2013,1000855714,GUZMÁN GODOY JORGE IVÁN,SIN MATRICULA,GRADUADO,ANTIGUO,NaN,3.600,3.227778,4.1250,4
66,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS 2013,1003519464,SIERRA SIERRA JULIETH ALEJANDRA,SIN MATRICULA,GRADUADO,ANTIGUO,NaN,4.175,3.909091,4.1125,2
70,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS 2013,1003519769,QUINTERO TORRES IVAN DARIO,SIN MATRICULA,GRADUADO,ANTIGUO,NaN,NaN,2.471429,4.4500,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
424,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS 2013,52836457,ERAZO BRAVO MONICA BIBIANA,SIN MATRICULA,GRADUADO,ANTIGUO,3.67,4.100,2.577778,NaN,3
425,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS 2013,80225566,RODRIGUEZ MEDINA CHRISTIAN BERNARDO,SIN MATRICULA,GRADUADO,ANTIGUO,NaN,NaN,4.037500,4.7000,1
483,2019-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS 2013,1069734073,PIÑEROS GUTIERREZ YEIMY LORENA,SIN MATRICULA,GRADUADO,ANTIGUO,NaN,2.400,2.214286,NaN,7
486,2019-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS 2013,1069750950,AREVALO RODRIGUEZ WILLIAM FABIAN,SIN MATRICULA,GRADUADO,ANTIGUO,NaN,NaN,0.000000,NaN,1
487,2019-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS 2013,1069758190,BELTRÁN LEÓN JHON FREDY,SIN MATRICULA,GRADUADO,ANTIGUO,NaN,NaN,0.000000,NaN,1

In [33]:
# Paso 1: Definir las áreas de formación clave
areas_clave = ['CIENCIAS BÁSICAS', 'CIENCIAS BÁSICAS DE INGENIERÍA', 'INGENIERÍA APLICADA', 'INSTITUCIONAL']

# Paso 2: Crear máscara booleana para inconsistencias
mask_inconsistentes = (
    (df_resumen_fusagasuga['SITUACION_ACTUAL'].str.strip().str.upper() == 'GRADUADO') &
    df_resumen_fusagasuga[areas_clave].isna().any(axis=1)
)

# Paso 3: Crear DataFrame limpio (excluyendo los inconsistentes)
df_resumen_limpio = df_resumen_fusagasuga[~mask_inconsistentes].reset_index(drop=True)

In [34]:
df_resumen_limpio

,PERIODO,FACULTAD,UNIDAD,PENSUM,DOCUMENTO,NOMBRES,MATRICULA_ACTUAL,SITUACION_ACTUAL,CATEGORIA_ACTUAL,CIENCIAS BÁSICAS,CIENCIAS BÁSICAS DE INGENIERÍA,INGENIERÍA APLICADA,INSTITUCIONAL,TOTAL_BAJO_RENDIMIENTO_REA
0,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1000136072,FORERO HERRERA TANIA NICKOLL,SIN MATRICULA,ACTIVO,CONTINUIDAD ACADEMICA - EGRESADO,3.553846,3.956154,3.951915,3.897200,2
1,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1000320087,MESA BLANCO LEONARDO JUAN,SIN MATRICULA,ACTIVO,ANTIGUO,3.310833,3.297368,3.661538,3.761000,9
2,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1000592838,BAUTISTA DIAZ DANIEL EDUARDO,SIN MATRICULA,ACTIVO,CONTINUIDAD ACADEMICA - EGRESADO,3.475000,3.625714,3.960278,3.890833,6
3,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1001346777,SUAREZ HEREDIA JUAN SEBASTIAN,SIN MATRICULA,EXCLUIDO BAJO RENDIMIENTO,ANTIGUO,3.171429,2.900000,3.100000,3.000000,7
4,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1003515700,ESCOBAR VASQUEZ JENIFFER DAYANA,SIN MATRICULA,EXCLUIDO BAJO RENDIMIENTO,ANTIGUO,3.328571,2.623529,3.900000,3.485714,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1047,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1105465272,VILLARREAL CASTILLO DIEGO ANDRES,SIN MATRICULA,ACTIVO,ANTIGUO,NaN,4.788000,3.710000,4.375000,0
1048,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1105840288,GONZALEZ GONZALEZ GIOVANNI STIVEN,SIN MATRICULA,ACTIVO,ANTIGUO,NaN,4.346000,3.720000,4.060000,0
1049,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1110233645,RODRIGUEZ MENDOZA DANIEL ESTEBAN,SIN MATRICULA,ACTIVO,ANTIGUO,NaN,4.274000,3.860000,4.080000,0
1050,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1117502702,CUENCA MORENO OLIVER DANILO,SIN MATRICULA,ACTIVO,ANTIGUO,NaN,3.806000,4.300000,3.665000,0
1051,2024-2,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,11951929,REYES CASTILLO BRAYAN MICHEL,SIN MATRICULA,ACTIVO,MOVILIDAD ACADEMICA ENTRANTE,NaN,NaN,4.076000,NaN,0

In [35]:
df_resumen_limpio["SITUACION_ACTUAL"].value_counts()

SITUACION_ACTUAL
ACTIVO                                 611
GRADUADO                               198
EXCLUIDO NO RENOVACION DE MATRICULA     77
INACTIVO                                67
EXCLUIDO BAJO RENDIMIENTO               51
EXCLUIDO CANCELACION SEMESTRE           20
EXCLUIDO TRANSFERENCIA INTERNA          15
EXCLUIDO TRANSFERENCIA INTERNA SA        5
EXCLUIDO ASIMILACION DE PENSUM           3
REVISION CARPETA GRADO                   3
SUSPENDIDO                               1
SUSPENSION UN PERIODO ACADEMICO          1
Name: count, dtype: int64

In [36]:
# Mapeo personalizado
mapa_desercion = {
    'ACTIVO': 0,
    'GRADUADO': 0,
    'REVISION CARPETA GRADO': 0,

    'INACTIVO': 1,
    'EXCLUIDO NO RENOVACION DE MATRICULA': 1,
    'EXCLUIDO BAJO RENDIMIENTO': 1,
    'EXCLUIDO CANCELACION SEMESTRE': 1,
    'EXCLUIDO TRANSFERENCIA INTERNA': 1,
    'EXCLUIDO TRANSFERENCIA INTERNA SA': 1,
    'EXCLUIDO ASIMILACION DE PENSUM': 1,
    'SUSPENDIDO': 1,
    'SUSPENSION UN PERIODO ACADEMICO': 1
}

# Nueva variable binaria
df_resumen_limpio['DESERTA'] = df_resumen_limpio['SITUACION_ACTUAL'].map(mapa_desercion)

In [37]:
df_resumen_limpio['DESERTA'].value_counts()

DESERTA
0    812
1    240
Name: count, dtype: int64

In [38]:
df_resumen_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1052 entries, 0 to 1051
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   PERIODO                         1052 non-null   object
 1   FACULTAD                        1052 non-null   object
 2   UNIDAD                          1052 non-null   object
 3   PENSUM                          1052 non-null   object
 4   DOCUMENTO                       1052 non-null   object
 5   NOMBRES                         1052 non-null   object
 6   MATRICULA_ACTUAL                1052 non-null   object
 7   SITUACION_ACTUAL                1052 non-null   object
 8   CATEGORIA_ACTUAL                1052 non-null   object
 9   CIENCIAS BÁSICAS                891 non-null    float64
 10  CIENCIAS BÁSICAS DE INGENIERÍA  1042 non-null   float64
 11  INGENIERÍA APLICADA             1020 non-null   float64
 12  INSTITUCIONAL                   1026 non-null   float64
 13  TOTAL_BAJO_RENDIMIENTO_REA      1052 non-null   int64
 14  DESERTA                         1052 non-null   int64
dtypes: float64(4), int64(2), object(9)
memory usage: 123.4+ KB

Se realizará un eliminación de variables que se considera que no tienen poder predictivo ya sea por redundacia o la cardinalidad de la variable es 1

In [39]:
df_resumen_limpio["MATRICULA_ACTUAL"].value_counts()

MATRICULA_ACTUAL
SIN MATRICULA    1052
Name: count, dtype: int64

In [40]:
df_resumen_limpio["SITUACION_ACTUAL"].value_counts()

SITUACION_ACTUAL
ACTIVO                                 611
GRADUADO                               198
EXCLUIDO NO RENOVACION DE MATRICULA     77
INACTIVO                                67
EXCLUIDO BAJO RENDIMIENTO               51
EXCLUIDO CANCELACION SEMESTRE           20
EXCLUIDO TRANSFERENCIA INTERNA          15
EXCLUIDO TRANSFERENCIA INTERNA SA        5
EXCLUIDO ASIMILACION DE PENSUM           3
REVISION CARPETA GRADO                   3
SUSPENDIDO                               1
SUSPENSION UN PERIODO ACADEMICO          1
Name: count, dtype: int64

In [41]:
df_resumen_limpio["CATEGORIA_ACTUAL"].value_counts()

CATEGORIA_ACTUAL
ANTIGUO                             843
CONTINUIDAD ACADEMICA - EGRESADO    112
PERDIDA DE CALIDAD DE ESTUDIANTE     67
NUEVO REINGRESO                      24
MOVILIDAD ACADEMICA ENTRANTE          3
EXPULSION                             1
NUEVO REGULAR                         1
SUSPENDIDO                            1
Name: count, dtype: int64

In [42]:
df_resumen_limpio = df_resumen_limpio.drop(columns=[
    "MATRICULA_ACTUAL",
    "SITUACION_ACTUAL",
    "CATEGORIA_ACTUAL"
])

In [43]:
df_resumen_limpio.to_excel('desempeño_areas_formacion.xlsx', index=False)

# Conlusiones
 - Se logró consolidar un conjunto de datos estructurado por estudiante, en el cual cada fila representa un registro único con su promedio de desempeño (REA) en cada una de las áreas de formación: Ciencias Básicas, Ciencias Básicas de Ingeniería, Ingeniería Aplicada e Institucional.

 - Se identificaron inconsistencias académicas en estudiantes cuya situación académica era “GRADUADO” pero que no tenían registro de notas en áreas críticas, lo cual permitió depurar la base y conservar únicamente los casos coherentes con el proceso formativo.

 - Se construyó una nueva variable binaria (DESERTA) a partir de la situación académica (SITUACION_ACTUAL), que permitirá abordar tareas de clasificación supervisada para la predicción del riesgo de deserción estudiantil.

 - La variable TOTAL_BAJO_RENDIMIENTO_REA permitió capturar el número de asignaturas en las que el estudiante ha obtenido un rendimiento bajo (nota menor a 3.0), generando un importante indicador de alerta temprana.

 - El conjunto final fue filtrado para incluir únicamente estudiantes de la sede Fusagasugá, permitiendo un análisis focalizado y alineado con la realidad local del programa académico.